### ISSUE TITLE
Allow filtering by fields of related models

### ISSUE THREAD

**Issue by jedrzej** [jedrzej/searchable#1]
The package now allows to search only among fiields of given searchable models. The scope of this issue is to add possibility to filter also fields of related models (one-to-one, many-to-one, many-to-many relations)

**Comment by lockncode** [comment]
I forked this last week and implemented a version of this (only a few lines of code).  If you want to check it out/test and let me know if you like the implementation and would like me to submit a pull request.  It's extremely simple and passes all your current tests (I haven't created any new ones because I haven't had time).

Usage is the same but to specify the model you use:

`return ['field_name', 'model:related_model_field_name'];`

And your query string would something like:

?model:related_model_field_name=john

**Comment by jedrzej** [comment]
Thanks @lockncode, I'll have a look :)

**Comment by MaksJS** [comment]
You should pull & merge, it works well !

**Comment by jedrzej** [comment]
Hey
I won't merge a functionality that is not covered by tests. So it needs to wait till one of us has time to add the tests. I plan to do this this week.
Thanks :)

**Comment by ArnaudTarroux** [comment]
Hi @jedrzej @lockncode !

Is in  branch 0.0.3 ? In this case, is it possible that you explain how it works ? 
Thanks a lot !!

**Comment by jedrzej** [comment]
Hi @ArnaudTarroux 
I've just pushed a branch filter-by-relation, it should allow filtering by relation using syntax that @lockncode  proposed. I tested it locally and it worked for me, I'm now trying to figure out how to write unit tests for that, as it's a bit hard to analyze the query Eloquent builds when I use whereHas(). It would be great if you could give it a try and see if it works for you.

Apart from whereHas(), Eloquent offers also whereDoesntHave() and I'd like to add handling that as well before releasing new version. I'm not sure what syntax to use in the URL for the negated version, any suggestions are appreciated :)

**Comment by Utwo** [comment]
What about 'model:another_model:related_model_field_name'? Can you search in 2 or more deep level relations?

**Comment by jedrzej** [comment]
What if you use nested relation's name like you'd normally do in whereHas()? E.g. 

`?related_model.another_model:field=3`

Won't that result in a call to

```
whereHas('related_model.another_model', function($builder) {
  $builder->where('field', 3);
})
```

**Comment by Utwo** [comment]
No, it's not working. 
If I run:
```
?relatedModel.anotherModel:field=3
```
I get:
```
Call to undefined method Illuminate\Database\Query\Builder::relatedModel_anotherModel()
in Builder.php line 2508
```

**Comment by patroniton** [comment]
Is there any update on if/when multiple relationship layers will be supported like in @Utwo's comment?

**Comment by jedrzej** [comment]
@patroniton it doesn't work because dots in URL are converted to underscores by PHP. So we'll need some new syntax to provide names of nested relations in the URL. I'm thinking about `?relatedModel:anotherModel:field=3`.
