### ISSUE TITLE
Allow relationship search

### ISSUE THREAD

**Issue by pedrommone** [jedrzej/searchable#21]
Today, is not possible to make relationship search.

**Comment by jedrzej** [comment]
Any more details? What's the Laravel verision? What is the relation definition and the query you run?

**Comment by pedrommone** [comment]
I'm using Laravel `5.2.13`. Today, we cannot make relationship searchs like:

```
->filtered(['plans.status'  => 'active']);
```

**Comment by jedrzej** [comment]
What does it mean that you cannot make searches? Are you getting any errors?

**Comment by jedrzej** [comment]
have you tried the syntax that is used in the docs? https://github.com/jedrzej/searchable#filtering-by-relation-attributes

You should use "plans:status", not "plans.status"

**Comment by pedrommone** [comment]
Again, my bad for dont look at docs correctly. Sorry for wasting your time.
