### ISSUE TITLE
Where between?

### ISSUE THREAD

**Issue by morloderex** [jedrzej/searchable#28]
Hello i have noticed there is no way to do a where between. 

And overriding the filter doesn't work either sense the filter method is beeing hit twice and not once with an array of the constraints. 

Consider this: 
`date[]=2016-07-26&date[]=2016-07-29`

This makes the dateProgressFilter beeing hit but its beeing hitted twice. 

So i have a single value to work with.. 

Is it possible to somehow get both constraint objects a once so i can do something like the fallowing:

`$builder->whereBetween()`

**Comment by jedrzej** [comment]
Have you tried using **(ge)** and **(le)** operators? As in:

`date[]=(ge)2016-07-26&date[]=(le)2016-07-29`
