### ISSUE TITLE
Search for content containg comma

### ISSUE THREAD

**Issue by kolydart** [jedrzej/searchable#37]
Is it possible to search for content, like "Smith, John"? 
Right now, it is looking for "Smith" OR "John".
Is there some kind of config to disable "OR" functionality for comma, or change it to another character?

**Comment by jedrzej** [comment]
There is no way to do that using configuration.

**Comment by kolydart** [comment]
ok. I've found a workaround for now. If I append (or prepend) a wildcard character, the search is performed. For the above mentioned example, "Smith, John" does not work, but "Smith, John%" works.
I consider it a minor disadvantage comparing to the huge time saving in development. So, just accept my thanks for your effort.

**Comment by jedrzej** [comment]
Nice, I didn't think of such workaround. I'm glad you got that to work. 
Without a workaround the only way I see to allow commas in the searched string is to use alternate syntax for **IN** search, which would be not backwards compatible. I could do that in a future release.
