### ISSUE TITLE
Problem with LIKE operator

### ISSUE THREAD

**Issue by torreswil** [jedrzej/searchable#44]
I have this problem, when i use LIKE operator. I want to filter %Carlos%, but dont work because Builder resolve this: "value" => b"Êrlos%".

![screenshot_1](https://user-images.githubusercontent.com/1329064/42585196-92817cec-84fa-11e8-8a18-173377f4bbbf.png)

`    protected function processSearchFilter(Builder $builder, Constraint $constraint)
    {
        // this logic should happen for LIKE/EQUAL operators only

        if ($constraint->getOperator() === Constraint::OPERATOR_LIKE || $constraint->getOperator() === Constraint::OPERATOR_EQUAL) {
            $builder->whereHas('tercero',function ($query) use ($constraint) {
                    $query->where('nombre1', $constraint->getOperator(), $constraint->getValue())
                        ->orWhere('nombre2', $constraint->getOperator(), $constraint->getValue())
                        ->orWhere('apellido1', $constraint->getOperator(), $constraint->getValue())
                        ->orWhere('apellido2', $constraint->getOperator(), $constraint->getValue())
                        ->orWhere('identificacion', $constraint->getOperator(), $constraint->getValue());

                });
            return true;
        }

        // default logic should be executed otherwise
        return false;
    }`

**Comment by jedrzej** [comment]
Hi @torreswil 
it seems that you need to encode the value of the seach parameter correctly. See the notice herre https://github.com/jedrzej/searchable#like-operators. If passed in the URL `%` character should be encoded as `%25`, so your query should be `search=%25carlos%25`
