### ISSUE TITLE
Multiple columns

### ISSUE THREAD

**Issue by vitorhugosg** [jedrzej/searchable#48]
Hello, pleasure, first of all to thank the developers for the beautiful work. I've been looking for something like this for some time.

Sorry I'm Brazilian so my English isn't very good, it's just technical.

I would like to know if with this tool I can do the research of several fields through just one attribute.

Example:

posts?search=%searchstring%

colums search: [title, desc, keyword]

**Comment by jedrzej** [comment]
Hi :) Thank you for your kind words, I'm glad you've found this package helpful.

The searchable package doesn't support filtering multiple fields with one query parameter out of the box, but you can easily provide your own filter logic for given custom field. See here for an example: https://github.com/jedrzej/searchable#overriding-default-filter-logic
